export enum SAPLanguages {
    English = 'English',
    Polish = 'Polish',
    German = 'German',

    /* TODO: extend the enum with all SAP-supported languages */
    // If language is not installed in target server,
    // user should be notified when connection is not established

    /*
    Afrikaans = 'Afrikaans',
    Arabic = 'Arabic',
    Bulgarian = 'Bulgarian',
    Catalan = 'Catalan',
    Chinese = 'Chinese',
    Chinese_Traditional = 'Chinese Traditional',
    Croatian = 'Croatian',
    Czech = 'Czech',
    Danish = 'Danish',
    Dutch = 'Dutch',
    Finnish = 'Finnish',
    French = 'French',
    Greek = 'Greek',
    Hebrew = 'Hebrew',
    Hungarian = 'Hungarian',
    Icelandic = 'Icelandic',
    Indonesian = 'Indonesian',
    Italian = 'Italian',
    Japanese = 'Japanese',
    Korean = 'Korean',
    Latvian = 'Latvian',
    Lithuanian = 'Lithuanian',
    Malay = 'Malay',
    Norwegian = 'Norwegian',
    Portuguese = 'Portuguese',
    Romanian = 'Romanian',
    Slovene = 'Slovene',
    Slovakian = 'Slovakian',
    Spanish = 'Spanish',
    Swedish = 'Swedish',
    Thai = 'Thai',
    Turkish = 'Turkish',
    Ukrainian = 'Ukrainian',
    */
};

export const LanguageCodes: Record<SAPLanguages, string> = {
    [SAPLanguages.Polish]: 'PL',
    [SAPLanguages.English]: 'EN',
    [SAPLanguages.German]: 'DE',

    /*
    [SAPLanguages.Afrikaans]: 'AF',
    [SAPLanguages.Arabic]: 'AR',
    [SAPLanguages.Bulgarian]: 'BG',
    [SAPLanguages.Catalan]: 'CA',
    [SAPLanguages.Chinese]: 'ZH',
    [SAPLanguages.Chinese_Traditional]: 'ZF',
    [SAPLanguages.Croatian]: 'HR',
    [SAPLanguages.Czech]: 'CS',
    [SAPLanguages.Danish]: 'DA',
    [SAPLanguages.Dutch]: 'NL',
    [SAPLanguages.Finnish]: 'FI',
    [SAPLanguages.French]: 'FR',
    [SAPLanguages.Greek]: 'EL',
    [SAPLanguages.Hebrew]: 'HE',
    [SAPLanguages.Hungarian]: 'HU',
    [SAPLanguages.Icelandic]: 'IS',
    [SAPLanguages.Indonesian]: 'ID',
    [SAPLanguages.Italian]: 'IT',
    [SAPLanguages.Japanese]: 'JA',
    [SAPLanguages.Korean]: 'KO',
    [SAPLanguages.Latvian]: 'LV',
    [SAPLanguages.Lithuanian]: 'LT',
    [SAPLanguages.Malay]: 'MS',
    [SAPLanguages.Norwegian]: 'NO',
    [SAPLanguages.Portuguese]: 'PT',
    [SAPLanguages.Romanian]: 'RO',
    [SAPLanguages.Slovene]: 'SL',
    [SAPLanguages.Slovakian]: 'SK',
    [SAPLanguages.Spanish]: 'ES',
    [SAPLanguages.Swedish]: 'SV',
    [SAPLanguages.Thai]: 'TH',
    [SAPLanguages.Turkish]: 'TR',
    [SAPLanguages.Ukrainian]: 'UK',
    */
};
